version: "3"
services:
  profile:
    image: profileservice
    container_name: profile
    depends_on:
      - auth
    environment:
      - SERVER_PORT=8080
      - AUTH_URL=http://auth:8080
    ports:
      - 8081:8080
  auth:
    image: authservice
    container_name: auth
    environment:
      - SERVER_PORT=8080
    ports:
      - 8082:8080
  gateway:
    image: gatewayservice
    depends_on:
      - profile
      - auth
    environment:
      - SERVER_PORT=8080
      - PROFILE_URL=http://profile:8080
      - AUTH_URL=http://auth:8080
    ports:
      - 8080:8080
